apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "app.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingressHost }}
    http:
      paths:
      - backend:
          service:
            name: {{ template "app.name" .}}
            port:
              number: 80
        pathType: ImplementationSpecific
        path: /
