apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ template "app.name" . }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80