replicaCount: 1

image:
  registry: 572357646341.dkr.ecr.eu-north-1.amazonaws.com
  repository: themis-aml-docs
  tag: latest
  pullPolicy: Always

resources:
  limits:
    cpu: "0.5"
    memory: "50Mi"
  requests:
    cpu: "0.1"
    memory: "50Mi"
